# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

production:
  adapter: postgresql
  database: 'postgres://nfzjheznhyigkb:YA9q3IoPfjpTuQVWjx3ZcHm0WE@ec2-176-34-127-73.eu-west-1.compute.amazonaws.com:5432/d64slru42if68c'
  pool: 5
  timeout: 5000
