common:
  flash:
    account_created: "Compte créé! Une confirmation de compte a été envoyée par e-mail."
    client_created: "Client créé!"
    update_complete: "Mise à jour terminée"
    administrator_deleted: "L'administrateur a été supprimé!"
    administrator_cant_be_deleted: "Vous ne pouvez pas supprimer cet administrateur!"
    no_access: "Vous n'avez pas accès à cette page"
    client_hided_or_recovered: "Le client a été caché / récupéré."
    cant_hide_client: "Impossible de masquer / récupérer le client"
    client_deleted: "Le client a été supprimé."
    client_cant_be_deleted: "Vous ne pouvez pas supprimer ce client"
    client_was_deactivated: "'Le client a été désactivé dans:% {time}'"
    unconfirmed_mail: "Vous n'avez pas confirmé votre courrier! Veuillez confirmer votre courrier."
    does_not_exist: "'Ce% {nom_classe} n'existe pas.'"
    interest_created: "Intérêt ajouté!"
    interest_updated: "Intérêt mis à jour!"
    interest_deleted: "Intérêt supprimé!"
    mentor_deleted: "Le mentor a été supprimé!"
    picture_created: "Image créée!"
    picture_updated: "Image mise à jour!"
    picture_deleted: "Image supprimée!"
    test_unfinished: "Le test n'est pas terminé"
    test_result_outdated: "Le test a été modifié. Les points d'intérêt sont dépassés!"
    test_result_deleted: "Résultat supprimé!"
    cant_find_client: "Impossible de trouver le client"
    cant_find_test: "Impossible de trouver le test"
    empty_test: "Le test est vide!"
    test_created: "Test créé!"
    test_updated: "Test mis à jour!"
    test_deleted: "Test supprimé!"
    test_cant_be_deleted: "Ce test a des résultats associés, veuillez les supprimer d'abord."
    language_created: "Langue créée!"
    translation_updated: "Traduction mise à jour!"
    role_updated: "Rôle mis à jour!"
  gender:
    man: "Homme"
    woman: "Femme"
    unknown: "Inconnue"
  boolean:
    true: "Oui"
    false: "Non"
  forms:
    search: "Chercher"
    confirm: "Confirmer"
    add: "Ajouter"
    delete: "Supprimer"
    edit: "Éditer"
    hide: "Cacher"
    recover: "Récupérer"
    delete_confirm: "Êtes-vous sûr?"
  menu:
    home: "Accueil"
    settings: "Réglages"
    my_profile: "Mon profil"
    log_out: "Se déconnecter"
    all: "Tout"
    profile: "Profil"
    create: "Créer"
    edit_profile: "Editer le profil"
  devise:
    resend_confirmations: "Renvoyer les instructions de confirmation"
    confirm_instructions: "Vous pouvez confirmer l'email de votre compte via le lien ci-dessous"
    reset_instructions: "Envoyez-moi les instructions de réinitialisation du mot de passe"
    password_reset: "Quelqu'un a demandé un lien pour changer votre mot de passe. Vous pouvez le faire via le lien ci-dessous."
    ignore_reset_request: "Si vous ne l'avez pas demandé, veuillez ignorer cet e-mail."
    password_stays_unchanged: "Votre mot de passe ne changera pas tant que vous n'aurez pas accédé au lien ci-dessus et en aurez créé un nouveau."
    confirm_account: "Confirmer mon compte"
    forgot_password: "Mot de passe oublié?"
    change_password: "Changer mon mot de passe"
    new_password: "Nouveau mot de passe"
    confirm_new_password: "Confirmer le nouveau mot de passe"
    change_your_password: "changez votre mot de passe"
    regards: "En ce qui concerne, AitScore."
    greetings: "Salutations"
    log_in: "S'identifier"
    remember_me: "Souviens-toi de moi"
    didnt_received_confirm: "Vous n'avez pas reçu d'instructions de confirmation?"
  kaminari:
    next: "Prochain"
    previous: "Précédent"
    first: "Première"
    last: "Dernier"
  unions:
    and: "et"

entities:
  interests:
    index: "Intérêts"
    interest: "L'intérêt"
    create_interest: "Créer de l'intérêt"
    all_interests: "Tous les intérêts"
    search_prompt: "Entrez le nom du centre d'intérêt"
    delete_confirm: "La suppression affectera les résultats. Êtes-vous sûr?"
    fields:
      name: "Nom"
  pictures:
    index: "Des photos"
    update: "Modifier l'image"
    create: "Créer une image"
    all_pictures: "Toutes les photos"
    search_prompt: "Entrez la description de l'image"
    related_interests: "Intérêts liés"
    delete_confirm: "La suppression affectera les résultats. Êtes-vous sûr?"
    add_interest: "Ajouter un intérêt"
    remove_interest: "Supprimer l'intérêt"
    has_audio_description: "Dispose d'une description audio"
    fields:
      image: "Image"
      description: "La description"
      weight: "Poids"
  tests:
    index: "Les tests"
    all_tests: "Tous les tests"
    update: "Modifier le test"
    create: "Créer un test"
    choosing_test: "Choix du test"
    back_to_profile: "Retour au profil"
    count_of_questions: "Nombre de questions"
    delete_confirm: "La suppression détruira tous les résultats de ce test. Êtes-vous sûr?"
    start: "Début"
    progress: "Le progrès"
    continue: "Continuer"
    started_tests: "Tests commencés"
    choose_test: "Choisissez test"
    no_started_tests: "Il n'y a pas de tests démarrés"
    add_picture: "Ajouter une question avec photo"
    add_youtube_video: "Ajouter une question avec une vidéo Youtube"
    remove_question: "Supprimer la question"
    fields:
      name: "Nom du test"
      version: "version"
      description: "La description"
      youtube_link: "Lien Youtube"
      youtube_video: "vidéo Youtube"
  users:
    password_prompt: "Laisser vide pour sauver l'ancien"
    confirmation_prompt: "Confirmer votre mot de passe"
    fields:
      email: "Email"
      password: "Mot de passe"
      password_confirmation: "Confirmation mot de passe"
  clients:
    client: "Client"
    index: "Clients"
    create: "Créer un client"
    choose_admin: "Choisissez l'administrateur local"
    choose_mentor: "Choisissez un mentor"
    search_prompt: "Entrez le nom de code"
    all_clients: "Tous les clients"
    delete_confirm: "La suppression du client supprimera également tous ses résultats. Êtes-vous sûr?"
    latest_results: "Derniers résultats des tests"
    fields:
      code_name: "Nom de code"
      gender: "Le genre"
      mentor: "Mentor"
      is_current_in_school: "Est-ce courant à l'école?"
  mentors:
    index: "Les mentors"
    mentor: "Mentor"
    all_mentors: "Tous les mentors"
    search_prompt: "Entrez le nom ou le nom de famille ici"
    create: "Créer un mentor"
    delete: "Supprimer le mentor"
    update: "Mettre à jour le mentor"
    choose_admin: "Choisissez l'administrateur local"
    choose_mentor: "Choisissez Mentor pour %{for}"
    delegate_prompt: "Pour la suppression, vous devez choisir un nouveau mentor pour les clients associés"
  local_administrators:
    administrator: "Administrateur"
    index: "Administrateurs locaux"
    all_administrators: "Tous les administrateurs"
    search_prompt: "Entrez le nom ou le nom de famille ici"
    create: "Créer un administrateur local"
    update: "Administrateur de mise à jour"
    delete: "Supprimer l'administrateur"
    delegate_prompt: "Pour la suppression, vous devez choisir un nouvel administrateur pour les mentors associés."
    choose_admin: "Choisissez l'administrateur pour %{for}"
  employees:
    phone_prompt: "Laissez vide si vous n'avez pas de téléphone"
    fields:
      name: "Nom"
      last_name: "Nom de famille"
      phone: "Téléphone"
      organisation: "Organisation"
      organisation_address: "Adresse de l'organisation"
  result_of_tests:
    update: "Mettre à jour le résultat"
    index: "Résultats du test"
    all_results_of: "Tous les résultats de"
    results_of: "Resultats de"
    result: "Résultat"
    result_outdated: "Ce résultat est obsolète"
    interest_points: "Points d'intérêt"
    average_answer: "Temps de réponse moyen au champ d'intérêt"
    timeline: "Chronologie"
    average_answer_short: "Temps de réponse moyen (sec)"
    attending_at_the_moment: "Participer au moment du test"
    time_of_answer: "Temps de réponse"
    time_of_answer_short: "Temps de réponse (sec)"
    heatmap: "Afficher la carte thermique"
    download_as: "Télécharger en tant que"
    question_deleted: "Cette question a été supprimée du test"
    earned_points: "Points d'intérêts gagnés"
    summary: "Sommaire"
    edit_request: "Si vous souhaitez modifier les résultats, demandez à votre mentor."
    maximum_interest_point: "Maximum de points dans le test"
    summary_test_result: "Résumé des résultats du test"
    show_detailed_result: "Afficher le résultat résumé détaillé"
    group_summary: "Résultat sommaire de tous les étudiants de"
    was_checked:
      thumbs_up: "Pouces vers le haut"
      thumbs_down: "Pouces vers le bas"
      question_mark: "Point d'interrogation"
    fields:
      test_name: "Nom du test"
      start_date: "Date de début"
      end_date: "Date de fin"
      ended: "Terminé"
      question_number: "Numéro de question"
      time: "Temps"
      answer: "Réponse"
      was_rewrited: "A été réécrit"
  questions:
    index: "Des questions"
    question: "Question"
  translations:
    index: "Traductions"
    all_translations: "Toutes les traductions"
  languages:
    create: "Créer une langue"
    language: "Langue"
    fields:
      name: "Abréviation"
  picture_interests:
    fields:
      picture: "Lien"
  test_availabilities:
    index: "Tester la disponibilité"

testing_process:
  finish_page: "Page de fin"
  congrats: "Félicitations, le test est terminé!"
  more_details: "plus de détails"
  most_rated: "Votre intérêt le plus apprécié est"
  most_second_rated: "Votre deuxième intérêt le plus choisi est"
  test_loading: "Le test est en cours de chargement, veuillez patienter"

static:
  home:
    first_line: "Le test d'intérêt du travail (AIT) a été développé par MPI Oosterlo, Thomas More Kempen et l'Université technique d'État de Volgograd. Une bonne adéquation entre la personne et le travail, où le travail correspond aux intérêts et aux possibilités, augmente considérablement la satisfaction au travail des personnes handicapées mentales. L'ACI a été développé pour montrer de l'intérêt pour certains domaines de travail sans égard aux compétences."
    second_line: "L'AIT a été développé comme un test visuel qui peut être effectué en ligne. L'AIT dresse un tableau des domaines de travail dans lesquels le sujet de test veut travailler ou non et fournit des informations complémentaires à d'autres méthodologies qui mesurent l'intérêt du travail. L'utilisateur voit une photo à la fois et peut ensuite indiquer sa préférence en sélectionnant le bouton rouge (négatif) ou vert (positif). Si l'utilisateur n'a aucune opinion sur une photo, il peut sauter cette photo."
    third_line: "Les photos sont divisées en différents domaines de travail (par exemple: travail de préparation des aliments, travail orienté client, travail administratif, etc.). Une fois le test terminé, les résultats montrent quelles zones de travail sont préférées par l'utilisateur."
    fourth_line: "L'objectif de l'AIT est de contrôler régulièrement les intérêts de notre groupe cible pour le travail"
    fives_line: "L'AIT est disponible pour les organisations qui travaillent avec des personnes handicapées mentales."
    six_line: "Êtes-vous intéressé à essayer le test gratuitement? Veuillez envoyer un e-mail à"
    seven_line: "Avez-vous déjà un compte?"

errors:
  field: "Champ"
  taken: "existe déjà"
  too_short: "trop court"
  too_long: "trop long"
  blank: "est vide"
  not_a_number: "pas un nombre"
  less_than: "c'est trop petit"
  invalid: "est invalide"
  confirmation: "ne correspond pas au mot de passe"
  not_found: "enregistrement avec une telle valeur est introuvable"
  attachment_invalid: "La pièce jointe doit être une image ou un gif"
  attachment_too_big: "L'attachement est trop grand"
  link_error: "Vous devez spécifier une image ou un lien YouTube"
  no_questions: "Le test est vide"
  testing_ended: "Le test est terminé"
  link_pattern: "Lien YouTube incorrect. Il doit s'agir de https://youtu.be/ <ID>, https://m.youtube.com/watch?v= <ID> ou https://www.youtube.com/watch?v= <ID>"
